/* FILENAME: UNITS.H
 * PROGRAMMER: MY6
 * PURPOSE: Globe project declaration module.
 * LAST UPDATE: 07.06.2014
 */

#ifndef __UNITS_H_
#define __UNITS_H_

#include "anim.h"

/* Функция создания объекта анимации */
my6UNIT * MY6_ClockUnitCreate( VOID );

/* Функция создания информационного объекта анимации */
my6UNIT * MY6_InfoUnitCreate( VOID );

#endif /* __UNITS_H_ */

/* END OF 'UNITS.H' FILE */
